[package]
name = "day01-tests"
version = "0.1.0"
authors = ["Perjéssy, Lóránt <lostlont@lostlont.hu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day01-core = { path = "../day01-core" }
